name: CheckBuild

on:
  push:
    branches: [master dev]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies (cached)
        run: bun install --frozen-lockfile
      - name: Check liniting
        run: bunx eslint . --max-warnings=0
      - name: Build
        run: bun run build
