name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    env:
      NIX_CONFIG: "extra-experimental-features = nix-command flakes"

    steps:
      - name: checkout depedencies
        run: nix shell nixpkgs#nodejs
      - uses: actions/checkout@v4
      - name: build
        run: nix develop .
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres 
      - name: Prepare
        run: cargo sqlx prepare --check
      - name: Build
        run: cargo build
